// 初回40案のシードデータ(内部生成済み・審査済み・2026-07-27監査反映)。
// - 採用16案: フルの撮影・語りの設計図 + 4週間×週4投稿のカレンダー配置済み
//   (WF-008はバドミントン=本人の競技経験としての使用承認により採用復帰・W2-4に配置)
// - 保留14案 / 却下9案 / リメイク1案(WF-040)
// - Week1の4案(WF-001〜004)は内容監査済み: 診断的表現の除去(001)・段階練習と中止判断(002)・
//   金額を価値の証明にしない(003)・未提供実績の禁止(004)
// UIの「初期データ投入」から pf_ideas に投入する(code unique制約で冪等・既存はスキップ)。
// 一次情報は素材DBの本人承認済み素材のみ使用。ないものは needs_material=true。

import type { IdeaDraft, IdeaScores, Material } from './types';

export const SEED_BATCH_ID = 'seed-2026-07';

type SeedEntry = Partial<Omit<IdeaDraft, 'material_ids'>> & {
  code: string;
  title: string;
  materialTitles?: string[]; // insert時に pf_materials.title → id へ解決
};

const BASE: Omit<IdeaDraft, 'code' | 'title'> = {
  batch_id: SEED_BATCH_ID,
  status: 'candidate',
  style: 'A',
  purpose_main: 'awareness',
  purpose_sub: '',
  pillar_main: 'beginner',
  pillar_sub: [],
  audience: 'beginner',
  concern: '',
  reason_to_watch: '',
  core_message: '',
  takeaway: '',
  hook_visual: '',
  hook_line: '',
  moves: [],
  camera_angles: '',
  comparison_footage: '',
  structure: '',
  talking_points: [],
  material_ids: [],
  needs_material: false,
  avoid_misunderstanding: '',
  safety_notes: '',
  closing_question: '',
  closing_style: '',
  comment_prompt: '',
  keywords: [],
  lesson_cta: false,
  lesson_cta_phrase: '',
  duration_sec: 45,
  shoot_difficulty: 1,
  edit_difficulty: 1,
  values_used: [],
  scores: {},
  score_total: 0,
  primary_metric: '',
  repurpose: '',
  remake_note: '',
  remake_of: null,
  duplicate_of: null,
  reject_reason: '',
  scheduled_week: null,
  scheduled_slot: null,
  production_status: 'not_started',
  required_materials: '',
  material_deadline: null,
  alternative_note: '',
};

const s = (v: Partial<IdeaScores>): Partial<IdeaScores> => v;

// ═══ 採用16案(4週間×週4投稿に配置済み) ═══════════════════

const ADOPTED: SeedEntry[] = [
  {
    code: 'WF-001', title: 'かかとを付けてしゃがめますか?', status: 'adopted',
    style: 'A', purpose_main: 'awareness', pillar_main: 'beginner', audience: 'beginner',
    scheduled_week: 1, scheduled_slot: 1,
    concern: '運動不足の自覚はあるが、自分の身体がいまどう動くのかを観察したことがない',
    reason_to_watch: 'その場で試して、自分の身体の動き方を観察できる参加型',
    core_message: 'しゃがむのは筋力だけの問題ではなく「使い方」。自分の動きを観察することが変化の入口になる',
    takeaway: 'かかとをつけたまましゃがんでみると、自分の身体の使い方のクセが見えてくる',
    hook_visual: '画面いっぱいで深いフルスクワットに一気に沈む(正面)',
    hook_line: 'かかとを付けたまま、深くしゃがめますか?',
    moves: ['フルスクワット(ディープスクワット)', 'かかと浮きの失敗例'],
    camera_angles: '正面固定+横からの比較カット',
    comparison_footage: 'かかとが浮く例(NG)とかかとが付く例(OK)の横並び',
    structure: '0-3秒フック実演 → 3-15秒 視聴者に試させる(3秒静止) → 15-35秒 どこで止まるか・どこが動きにくいかを観察するポイント(かかと・足首・股関節) → 35-45秒 動物は毎日この姿勢という一言 → 締めの問い',
    talking_points: ['今この場で試してみて(3秒静止)', 'できる/できないの判定ではなく「どこで止まるか」の観察', 'かかと・足首・股関節のどこが動きにくいかに目を向ける', '一つの動きだけで原因は決められない。今日は観察まで', '無理に深くしゃがまない(痛みが出たら中止)'],
    avoid_misunderstanding: '診断・医学的テストとして扱わない(「足首に問題がある証拠」「身体年齢が分かる」「不調の原因が分かる」等は言わない)。しゃがめない=ダメではなく、観察のきっかけとして伝える',
    safety_notes: '膝や腰に痛みがある人は無理をしない旨をテロップで明示',
    closing_question: 'あなたの身体は、何を忘れていると思いますか?',
    closing_style: '「できなかった人、それ伸びしろです」と笑って締める',
    comment_prompt: 'できた/できなかった、コメントで教えてください',
    keywords: ['しゃがめない', 'フルスクワット', '足首 硬い', '身体テスト'],
    lesson_cta: false, duration_sec: 45, shoot_difficulty: 1, edit_difficulty: 1,
    values_used: ['practical', 'clarity', 'body_awareness', 'surprise'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 3, visual_value: 2, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '再生数・新規視聴者',
    repurpose: '「○○できますか?」テスト型シリーズの第1弾として量産可能',
  },
  {
    code: 'WF-002', title: 'Beastポジション、押さえるのは3つだけ', status: 'adopted',
    style: 'C', purpose_main: 'save', pillar_main: 'technique', audience: 'hesitant',
    scheduled_week: 1, scheduled_slot: 2,
    concern: 'Animal Flowの動画を見ても、何から練習すればいいか分からない',
    reason_to_watch: '全ムーブの土台になる基本姿勢を3ポイントに絞った保存版',
    core_message: 'どんな複雑なフローも、Beastという1つの姿勢から始まる',
    takeaway: 'Beastは「手の位置・膝2cm・背中フラット」の3点だけ押さえればいい',
    hook_visual: '四つ這いから膝を2cm浮かせた静止姿勢をドンと見せる(横)',
    hook_line: 'この姿勢、10秒キープできたら体幹はかなり強いです',
    moves: ['Beast(ビースト)ポジション', 'よくある間違い(腰が高い/背中が丸い)'],
    camera_angles: '真横固定がメイン、手元アップ1カット',
    comparison_footage: 'NG姿勢(腰高)→OK姿勢の切り替え',
    structure: '0-2秒フック静止 → 2-10秒 10秒チャレンジ誘導 → 10-35秒 3ポイントを順に実演(テロップ番号) → 35-50秒 NG/OK比較 → 保存訴求で締め',
    talking_points: ['手は肩の真下', '膝は床から2cmだけ', '背中は一枚の板', '腰が高くなるのが一番多い間違い', 'きつい人は膝を床につけたまま形を作ればOK(段階練習)', '秒数よりフォームの質が先'],
    avoid_misunderstanding: '「体幹トレの代わり」ではなく「全ムーブの共通土台」であること。秒数を競う耐久トレーニングにしない(目的はフォームの質)',
    safety_notes: '手首や肩に痛み・違和感が出たらすぐ中止する旨をテロップで明示。事前に手首の準備運動を推奨(別動画に誘導可)',
    closing_question: '10秒、何秒目でプルプルきましたか?',
    closing_style: '「これができたら次の動きに進めます。保存してあとで試してください」',
    comment_prompt: '何秒キープできたかコメントで',
    keywords: ['Animal Flow 基本', 'ビースト', '体幹', '四つ這いトレーニング'],
    lesson_cta: false, duration_sec: 50, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['expertise', 'clarity', 'info_density', 'practical'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 2, visual_value: 3, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '保存数・保存率',
    repurpose: '「基本ムーブ3ポイント」シリーズとしてCrab/Ape等に横展開',
  },
  {
    code: 'WF-003', title: '上海で、24万円を即決した日', status: 'adopted',
    style: 'B', purpose_main: 'persona', pillar_main: 'mind', audience: 'calm',
    scheduled_week: 1, scheduled_slot: 3,
    materialTitles: ['上海でAnimal Flowに出会い24万円を即決した話'],
    concern: '自分を変えたい気持ちはあるが、きっかけが掴めない',
    reason_to_watch: '「理屈抜きで人生が動いた瞬間」の実話。共感と好奇心',
    core_message: '身体が先に「これだ」と分かる瞬間がある。頭で考える前に',
    takeaway: '心が動いた瞬間の直感は、案外正しい',
    hook_visual: '床に座って落ち着いたトーンで話し始める(自然光・静かな室内)',
    hook_line: '妻に連れられて行った教室で、24万円を即決しました',
    moves: ['(語りメイン)最後に軽くBeastから流れる動きを一つ'],
    camera_angles: '正面固定1カメ。語り7割+ラスト実演',
    comparison_footage: 'なし',
    structure: '0-3秒 金額フック(興味喚起まで) → 3-20秒 上海の教室での出会い → 20-40秒 なぜそこまで惹かれたのか(身体の新しい可能性が開けた感覚)と「日本に持ち帰らなければ」と感じた瞬間 → 40-55秒 いま床の上にいる理由 → 静かに動いて終わる',
    talking_points: ['妻に連れられて行った謎の教室', 'インストラクターの一言で何かがつながった', 'なぜ惹かれたのか: 身体の新しい可能性が開けた感覚', '理屈はあとから付いてきた', 'だから今、床の上にいる'],
    avoid_misunderstanding: '金額の大きさをAnimal Flowの価値の証明にしない(「高いから本物」という構成にしない)。高額課金を勧める話でもない。中心は「なぜ惹かれたのか」',
    safety_notes: '特になし',
    closing_question: 'あなたが最近、理屈抜きで心が動いたことは何ですか?',
    closing_style: '語り終わりにゆっくり一呼吸おいて、動きだけで終わる',
    comment_prompt: '直感で決めてよかったこと、あれば教えてください',
    keywords: ['Animal Flow きっかけ', '上海', '人生が変わった瞬間'],
    lesson_cta: false, duration_sec: 55, shoot_difficulty: 1, edit_difficulty: 1,
    values_used: ['experience', 'relatability', 'calm_world', 'firsthand'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 3, visual_value: 2, takeaway_value: 2, originality: 3, brand_fit: 3, filmability: 3 }),
    primary_metric: '平均視聴時間・共感コメント',
    repurpose: 'ストーリー語りシリーズの第1話。ブログ記事化してサイト掲載',
  },
  {
    code: 'WF-004', title: '日本語教師が運動を教えると、説明がこうなる', status: 'adopted',
    style: 'C', purpose_main: 'trust', pillar_main: 'backstage', audience: 'hesitant',
    scheduled_week: 1, scheduled_slot: 4,
    materialTitles: ['日本語教師×野生身体研究家という肩書き'],
    concern: '運動の説明は専門用語が多くて、動画を見ても真似できない',
    reason_to_watch: '「教えるプロ」による説明の分かりやすさそのものが価値',
    core_message: '伝わらないのは学ぶ側のせいではなく、説明の設計の問題',
    takeaway: 'いい先生は「できない人がどこで詰まるか」から逆算して教える',
    hook_visual: 'ホワイトボード or 紙に「専門用語だらけの説明」を見せて破る',
    hook_line: '本業は日本語教師です。だから説明には、こだわりがあります',
    moves: ['Beastのセットアップを「専門用語版」と「翻訳版」で2回説明'],
    camera_angles: '正面固定。説明パートは上半身、実演パートは全身',
    comparison_footage: '同じ動きの「伝わらない説明」vs「伝わる説明」',
    structure: '0-3秒 肩書きフック → 3-15秒 専門用語版の説明(わざと分かりにくく) → 15-40秒 同じ動きを翻訳版で説明 → 40-55秒 外国人に日本語を教える技術と同じという種明かし → 締め',
    talking_points: ['専門用語は「知っている人」にしか届かない', '日本語教育は「伝わらない前提」から設計する', '身体の説明も同じ', 'wild-flowのレッスンはこの設計で作っている'],
    avoid_misunderstanding: '他の指導者の説明を馬鹿にする内容にしない。日本語教師としての勤務先・年数・教えた人数など未提供の実績は言わない。中心は「複雑な動きを初心者が理解できる小さな単位に分解して伝える」というwild-flowの指導価値',
    safety_notes: '特になし',
    closing_question: '「説明が分かりやすくて助かった」経験、ありますか?',
    closing_style: '「分かりにくかったら、それは私の宿題です」と笑って締める',
    comment_prompt: '運動の説明で挫折した経験、コメントで教えてください',
    keywords: ['分かりやすい 説明', '日本語教師', '運動 初心者'],
    lesson_cta: true,
    lesson_cta_phrase: 'この説明の仕方でやるレッスンに興味があれば、プロフィールからサイトを覗いてみてください',
    duration_sec: 55, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['firsthand', 'clarity', 'rare_angle', 'relatability'],
    scores: s({ target_clarity: 2, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 3, originality: 3, brand_fit: 3, filmability: 3 }),
    primary_metric: 'プロフィール閲覧・サイト遷移',
    repurpose: '「翻訳して教える」シリーズとして他ムーブにも展開',
  },
  {
    code: 'WF-005', title: '筋力があっても、この動きが難しい理由', status: 'adopted',
    style: 'A', purpose_main: 'awareness', pillar_main: 'ability', audience: 'lifter',
    scheduled_week: 2, scheduled_slot: 1,
    concern: '筋肉はあるのに動きが硬い。可動域が狭いと感じている',
    reason_to_watch: '「筋力とは別のスキルがある」という発見型の逆張りフック(特定の誰かを見下さない)',
    core_message: '筋力の大きさと、体重移動・協調性・身体操作は異なる能力。どちらにも価値があり、掛け算で身体は自由になる',
    takeaway: '重いものを動かす力と、身体を思いどおりに動かす力は別の能力。どちらも鍛えられる',
    hook_visual: 'ゆっくりしたScapula(肩甲骨)コントロール系の動きをアップで見せる',
    hook_line: '重いバーベルを挙げられる人でも、この動きは意外と苦戦します',
    moves: ['スキャプラプッシュ(肩甲骨の分離)', 'ゆっくりした体重移動のコントロール'],
    camera_angles: '背面アップ(肩甲骨)+横からの全身',
    comparison_footage: '速い反動で誤魔化す例 vs ゆっくり制御する例',
    structure: '0-3秒 逆張りフック → 3-20秒 動きの実演(視聴者にも試させる) → 20-40秒 筋力と操作は別スキルという説明 → 40-50秒 筋トレは否定しない、掛け算という話 → 締め',
    talking_points: ['できなくても筋力不足ではない(別の能力の話)', '神経系のコントロールの問題', '筋トレで作った筋肉を「使える」ようにするのがこの練習', 'どちらの能力にも価値がある。両方やる人が一番伸びる'],
    avoid_misunderstanding: '筋トレを否定しない(動画内で明言する)。「できない人」を見下す構成にしない。本人の挙上重量など未確認の実績数値は言わない(一般論として話す)',
    safety_notes: '肩に違和感がある人は小さい可動域から',
    closing_question: 'あなたの身体、筋力と操作どちらが先行していますか?',
    closing_style: '「筋トレしてる人ほど伸びます」とポジティブに締める',
    comment_prompt: 'できたかどうか、トレーニング歴と一緒にコメントで',
    keywords: ['筋トレ 可動域', '肩甲骨 動かない', '身体操作'],
    lesson_cta: false, duration_sec: 50, shoot_difficulty: 2, edit_difficulty: 2,
    values_used: ['surprise', 'challenge', 'body_awareness', 'expertise'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 3, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 2, filmability: 3 }),
    primary_metric: '再生数・フォロー',
    repurpose: '「筋トレ勢チャレンジ」シリーズ化。ジム系との相互反応も狙える',
  },
  {
    code: 'WF-006', title: '朝、ベッドの横で1分だけ', status: 'adopted',
    style: 'A', purpose_main: 'save', pillar_main: 'beginner', audience: 'beginner',
    scheduled_week: 2, scheduled_slot: 2,
    concern: '運動を始めたいが時間がない。何から始めればいいか分からない',
    reason_to_watch: '起きてすぐ・畳1枚・1分で完結する再現性の高さ',
    core_message: '運動習慣は「小ささ」から始まる。1分の床時間で身体は変わり始める',
    takeaway: '朝の1分、床に手をつくだけで身体のスイッチは入る',
    hook_visual: '寝間着のままベッド横の床に降りて四つ這いになる生活感のある画',
    hook_line: '起きて1分、これだけやってください',
    moves: ['キャットカウ(背骨の波)', 'ワイパーツイスト(股関節回旋)', 'ベビークロール数歩'],
    camera_angles: '横からの固定1カメ(生活空間そのまま)',
    comparison_footage: 'なし',
    structure: '0-3秒 フック → 3-45秒 3ムーブを各15秒ずつ実演(テロップで回数) → 45-55秒 「これで今日の身体が変わる」→ 保存訴求',
    talking_points: ['着替えなくていい', '3つで1分', '完璧にやらなくていい', '続けるコツは小さくすること'],
    avoid_misunderstanding: '「これだけで痩せる」等の効果の誇張をしない',
    safety_notes: '寝起きは関節が硬いので反動をつけない',
    closing_question: '明日の朝、どれか1つだけでもやってみませんか?',
    closing_style: '「保存しておけば、明日の朝の自分が思い出します」',
    comment_prompt: 'やったら「朝1分やった」とコメントください。全部に返します',
    keywords: ['朝 ストレッチ', '1分 運動', 'ズボラ 運動習慣'],
    lesson_cta: false, duration_sec: 55, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['practical', 'clarity', 'calm_world', 'info_density'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '保存数・保存率',
    repurpose: '朝/夜/デスク横など「生活の隙間1分」シリーズ化',
  },
  {
    code: 'WF-007', title: 'できない日があっていい', status: 'adopted',
    style: 'B', purpose_main: 'persona', pillar_main: 'mind', audience: 'calm',
    scheduled_week: 2, scheduled_slot: 3,
    concern: 'SNSの「毎日継続」「成長しろ」という空気に疲れている',
    reason_to_watch: '運動系なのに急かさない、比べさせない世界観への共感',
    core_message: '身体との付き合いは記録更新ではなく対話。できない日も情報のうち',
    takeaway: '「今日はここまで」と言える人が、いちばん長く続く',
    hook_visual: '床にあぐらで座り、窓の光の中でゆっくり肩を回している画',
    hook_line: '今日は、あんまり動けませんでした。それでいいと思っています',
    moves: ['座位でのゆっくりした背骨の動き(語りながら)'],
    camera_angles: '正面やや引きの固定1カメ',
    comparison_footage: 'なし',
    structure: '0-3秒 逆張りの告白フック → 3-25秒 「毎日100%」を目指すと続かない話 → 25-45秒 身体の声を聞く=できない日を責めない → 45-60秒 ゆっくり動きながら静かに締める',
    talking_points: ['続かないのは意志が弱いからではない', '身体のコンディションは毎日違う', 'できない日は「休む情報」をくれた日', '比べる相手は昨日の自分ですらなくていい'],
    avoid_misunderstanding: '「努力不要」と言っているのではない。続けるための力の抜き方の話',
    safety_notes: '特になし',
    closing_question: '最近、自分の身体の声を聞けていますか?',
    closing_style: '言い切らず、余白を残してフェードアウト',
    comment_prompt: '「今日は休んだ」も立派な報告です。コメントでどうぞ',
    keywords: ['運動 続かない', '自己肯定', 'マインドフルネス 運動'],
    lesson_cta: false, duration_sec: 60, shoot_difficulty: 1, edit_difficulty: 1,
    values_used: ['calm_world', 'relatability', 'body_awareness', 'rare_angle'],
    scores: s({ target_clarity: 2, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '平均視聴時間・共感コメント',
    repurpose: '穏やか語りシリーズ。noteやブログの長文記事にも展開可能',
  },
  {
    // 【2026-07-27 再審査で採用復帰】バドミントンは「本人の競技経験」として使用承認された。
    // kawabadoの運営・数値・実績には言及しない構成に修正済み(主宰者→競技経験者)。
    code: 'WF-008', title: 'バドミントンの切り返しが遅い人へ', status: 'adopted',
    style: 'C', purpose_main: 'trust', pillar_main: 'application', audience: 'athlete',
    scheduled_week: 2, scheduled_slot: 4,
    materialTitles: ['バドミントン競技の本人経験(左右差・切り返し・体重移動・連動)'],
    concern: '切り返しや一歩目が遅い。競技練習以外で何をすべきか分からない',
    reason_to_watch: 'バドミントンを続けている競技経験者が、自分の身体で感じた接点を競技目線で語る',
    core_message: '切り返しの速さは脚力だけではない。床を押す感覚の練習が土台になる(本人の実感として)',
    takeaway: '四足で床を押す感覚は、コートの一歩目にそのままつながる',
    hook_visual: 'バドミントンのフットワーク(サイドステップ)→四足の切り返しを連続で見せる',
    hook_line: 'バドミントンやってる人、切り返しの遅さ、脚力のせいにしていませんか',
    moves: ['Beastからの方向転換', 'サイドキックスルー', '(比較用)バドミントンのフットワーク'],
    camera_angles: '全身が入る引きの固定+足元アップ',
    comparison_footage: 'コートでの切り返しと床での四足切り返しの並列編集',
    structure: '0-3秒 競技者フック → 3-15秒 コートの動きと床の動きの比較 → 15-40秒 床を押す→身体が動き出す感覚の話+実演 → 40-55秒 自分もバドミントンを続けていて、体重移動や左右差で実感していることを一言 → 締め',
    talking_points: ['一歩目は脚力ではなく床反力の伝達', '四足は全身で床を押す練習', '競技者として自分の身体でこの接点を検証している', '競技練習と置き換えるのではなく足し算'],
    avoid_misunderstanding: '「競技練習の代替になる」「必ず上達する」とは言わない(補完・本人の実感の範囲)。kawabadoの参加人数・実績・参加者には一切触れない',
    safety_notes: '床での切り返しは滑らないマットの上で',
    closing_question: 'あなたの競技で「床を押す」感覚、意識したことありますか?',
    closing_style: '「競技をやっている人ほど、床の上の練習は面白いはず」',
    comment_prompt: '何の競技をやっているかコメントで教えてください。競技別に作ります',
    keywords: ['バドミントン フットワーク', '切り返し 速く', 'アジリティ'],
    lesson_cta: true,
    lesson_cta_phrase: '競技者向けの身体操作は、サイトの野生診断から自分の伸びしろを見てみてください',
    duration_sec: 55, shoot_difficulty: 2, edit_difficulty: 2,
    values_used: ['firsthand', 'expertise', 'rare_angle', 'practical'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 3, brand_fit: 2, filmability: 2 }),
    primary_metric: 'プロフィール閲覧・サイト遷移・質問',
    repurpose: '競技別応用シリーズの第1弾(コメントの競技名から次作を決める)',
  },
  {
    // 【2026-07-27 再確認】この企画は「これから始めるDay1」であり過去の検証記録は不要。
    // 必要素材(現在地の記録)は撮影当日に生まれるため needs_material を解除、制作進捗は未着手。
    code: 'WF-009', title: '初日、全然できませんでした(30日検証スタート)', status: 'adopted',
    style: 'A', purpose_main: 'awareness', pillar_main: 'growth', audience: 'hesitant',
    scheduled_week: 3, scheduled_slot: 1,
    concern: '難しそうな動きは、才能がある人にしかできないと思っている',
    reason_to_watch: '「できない状態」から始まる検証記録。続きが気になる構造',
    core_message: '今日から30日間、苦手な一つの動きを毎日短時間練習する。変化だけでなく停滞や失敗も記録する',
    takeaway: '最初は誰でもできない。記録すれば30日後の自分と比べられる',
    hook_visual: '難しめのムーブに挑戦して崩れる実際の失敗カット',
    hook_line: 'はい、できません。今日がDay 1です',
    moves: ['挑戦対象のムーブ(撮影時の練習中の動きから選定)', '現時点の到達点の記録'],
    camera_angles: '定点固定(毎回同じ位置・同じ画角で撮ると比較が効く)',
    comparison_footage: 'Day1の記録(以後の動画で比較素材になる)',
    structure: '0-3秒 失敗カット → 3-15秒 30日検証の宣言とルール(毎日短時間・記録は正直に) → 15-40秒 今日の練習(段階練習の最初のステップ) → 40-50秒 現在地を同じ角度の定点で記録 → 「Day30で会いましょう」',
    talking_points: ['今日がDay1。まず現在地を同じ角度で撮る', '毎日短時間でいい。練習時間と意識した点を簡単に記録', '30日でできるようになるとは約束しない', '停滞も失敗もそのまま残す', '痛みや強い違和感が出たら中止する'],
    avoid_misunderstanding: '「30日で必ずできる」と約束しない(習得期間は人による)。最終結果は「完成したか」ではなく「何が変わったか」で評価する',
    safety_notes: '難しいムーブは必ず段階練習から。無理な着地をしない。途中で痛みや強い違和感があれば検証を中止する',
    closing_question: 'あなたが「30日だけ試してみたいこと」は何ですか?',
    closing_style: '「Day 30、見届けてください」とフォロー動機で締める',
    comment_prompt: '一緒に30日チャレンジする人、宣言コメントどうぞ',
    keywords: ['30日チャレンジ', 'Animal Flow 練習', 'ビフォーアフター'],
    lesson_cta: false, duration_sec: 50, shoot_difficulty: 2, edit_difficulty: 2,
    values_used: ['growth', 'challenge', 'relatability', 'experience'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 3, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: 'フォロー・再生数',
    repurpose: 'Day10/Day20/Day30の続編が自動的に生まれる。撮影した記録は素材DBに「検証記録」として蓄積していく',
  },
  {
    code: 'WF-010', title: 'Beastで手首に負担を感じる人へ。始める前に確認したい3つ', status: 'adopted',
    style: 'C', purpose_main: 'save', pillar_main: 'technique', audience: 'beginner',
    scheduled_week: 3, scheduled_slot: 2,
    concern: '四つ這いの姿勢で手首に負担を感じて、床トレーニングが続かない',
    reason_to_watch: '床運動の最初の壁「手首の負担」への具体的な準備。保存して毎回使える',
    core_message: '手首の負担は準備と荷重の載せ方で変わる。原因を一つに決めつけず、肩や体重配分も含めて身体全体の使い方を見る',
    takeaway: '床に手をつく前の3つの確認で、手首への負担のかかり方が変わる',
    hook_visual: '四つ這いに入りかけて手首を気にして止まる→手元アップで正しい手の着き方',
    hook_line: '四つ這いで手首がつらい人、始める前に3つだけ確認してください',
    moves: ['手首の準備運動(前後・左右・リストリフト)', '指の付け根で床を押す荷重の載せ方', '肩の位置と体重配分の確認', '膝つきで負荷を下げる形'],
    camera_angles: '手元アップ中心+四つ這いの全身',
    comparison_footage: '手のひらベタ置き(NG)と指で床を掴む(OK)のアップ比較',
    structure: '0-3秒 共感フック → 3-15秒 負担がかかりやすい載せ方の話 → 15-45秒 確認3つを実演(①手首の準備運動 ②指の付け根で押す ③肩の位置と体重配分) → 45-55秒 つらければ膝をついて負荷を下げてよい → 保存訴求',
    talking_points: ['すでに痛みがある人は無理に続けない', '床に着く前に手首を起こす準備', '手のひら全体でなく指の付け根で押す', '手首だけでなく肩の位置や体重配分も関係することがある', 'つらければ膝をついて負荷を下げてOK'],
    avoid_misunderstanding: '痛みの改善・治療・予防を断言しない。痛みの原因を特定しない(「あなたは◯◯が原因」と言わない)。Animal Flowを行えば痛みがなくなるとは言わない',
    safety_notes: 'すでに痛みがある場合は無理に行わない。強い痛みや続く症状は専門家(医療機関)への相談を促すテロップを入れる。診断はしない',
    closing_question: 'あなたが床運動でつまずいた最初の壁はどこでしたか?',
    closing_style: '「床の上の時間が快適になると、全部が変わります。保存してどうぞ」',
    comment_prompt: '手首以外でつまずいた場所、コメントで教えてください',
    keywords: ['四つ這い 手首', 'Beast 手首 負担', '手首 準備運動', 'プランク 手首 つらい'],
    lesson_cta: false, duration_sec: 55, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['expertise', 'practical', 'clarity', 'body_awareness'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '保存数・質問コメント',
    repurpose: '「床運動の壁」シリーズ(膝が痛い/肩がすくむ等)に展開',
  },
  {
    code: 'WF-011', title: 'あの難しそうな動き、分解すると3段階です', status: 'adopted',
    style: 'A', purpose_main: 'awareness', pillar_main: 'beginner', audience: 'hesitant',
    scheduled_week: 3, scheduled_slot: 3,
    concern: 'SNSで見るAnimal Flowはかっこいいが、自分にできる気がしない',
    reason_to_watch: '完成形→分解→運動経験がなくても始められる第1段階、という希望が見える構成',
    core_message: 'どんな複雑な動きも段階に分解できる。入口は誰にでも開いている',
    takeaway: '「無理そう」は分解していないだけ。第1段階は今日できる',
    hook_visual: '流れるようなフロー(完成形)を3秒だけ見せる',
    hook_line: 'これ、無理そうに見えますよね。分解します',
    moves: ['完成形のフロー(短く)', '第1段階(静止姿勢)', '第2段階(片方の動き)', '第3段階(つなげる)'],
    camera_angles: '完成形は引き、分解は横からの中間距離',
    comparison_footage: '完成形と第1段階の並列(こんなに簡単になる、の可視化)',
    structure: '0-3秒 完成形フック → 3-10秒 「分解します」宣言 → 10-45秒 3段階を順に実演(視聴者は第1段階だけ試す) → 45-55秒 第1段階ができれば道は続いている → 締め',
    talking_points: ['完成形から逆算しない、第1段階から積む', '第1段階は運動経験ゼロでもできる', '段階が見えると怖くなくなる', '焦らなくていい、段階は逃げない'],
    avoid_misunderstanding: '「簡単ですぐできる」ではなく「段階を踏めば近づける」',
    safety_notes: '第2段階以降は無理をしない。痛みが出たら第1段階に戻る',
    closing_question: '第1段階、今日試したらコメントで教えてもらえますか?',
    closing_style: '「入口は思っているより低い場所にあります」',
    comment_prompt: '分解してほしい「無理そうな動き」をコメントで募集',
    keywords: ['Animal Flow 初心者', '段階練習', '難しい 動き'],
    lesson_cta: false, duration_sec: 55, shoot_difficulty: 2, edit_difficulty: 2,
    values_used: ['clarity', 'challenge', 'practical', 'visual_pleasure'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 3, visual_value: 3, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 2 }),
    primary_metric: '再生数・新規視聴者・コメント',
    repurpose: 'コメントで募集した動きを次回の「分解シリーズ」にする循環構造',
  },
  {
    code: 'WF-012', title: 'wild-flowのレッスンで、しない事を3つ決めています', status: 'adopted',
    style: 'B', purpose_main: 'trust', pillar_main: 'backstage', audience: 'calm',
    scheduled_week: 3, scheduled_slot: 4,
    concern: 'レッスンや教室は「厳しくされそう」「ついていけなさそう」で怖い',
    reason_to_watch: '「しないことリスト」という逆張りの自己紹介。安心感の設計',
    core_message: 'wild-flowは急かさない・比べさせない・置いていかない場所',
    takeaway: 'いい運動の場は「何をするか」より「何をしないか」で決まる',
    hook_visual: '床に座って指を3本立てる。静かな室内',
    hook_line: '私のレッスンでは、しないと決めていることが3つあります',
    moves: ['(語りメイン)合間に穏やかな動きのカットを挿入'],
    camera_angles: '正面固定。Bロールで床の動きのカットを2〜3枚',
    comparison_footage: 'なし',
    structure: '0-3秒 フック → 3-45秒 しないこと3つを順に(①急かさない ②人と比べさせない ③できない事を放置しない) → 45-60秒 なぜそう決めたか(ブランドの考え) → 静かに締め',
    talking_points: ['急かさない: 身体の変化は人それぞれのペース', '比べさせない: 隣の人は関係ない', '置いていかない: できない所は分解して戻る', 'この3つを守れる場を作りたかった'],
    avoid_misunderstanding: '他の教室・指導者の批判に聞こえないよう「自分の決め事」として話す',
    safety_notes: '特になし',
    closing_question: 'あなたが運動の場に求める「安心」はなんですか?',
    closing_style: '「そういう場所を作っています」とだけ言って終わる',
    comment_prompt: '教室系で嫌だった経験・よかった経験、どちらでも',
    keywords: ['レッスン 雰囲気', '運動 苦手 教室', 'wild-flow'],
    lesson_cta: true,
    lesson_cta_phrase: '概要はプロフィールのサイトに置いてあります。見るだけでも大丈夫です',
    duration_sec: 60, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['calm_world', 'firsthand', 'relatability', 'expertise'],
    scores: s({ target_clarity: 2, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 3, brand_fit: 3, filmability: 3 }),
    primary_metric: 'プロフィール閲覧・サイト遷移・体験希望',
    repurpose: 'レッスンページのコピーとしてサイトに転用可能',
  },
  {
    code: 'WF-013', title: '立ったまま靴下、履けますか?', status: 'adopted',
    style: 'A', purpose_main: 'awareness', pillar_main: 'ability', audience: 'beginner',
    scheduled_week: 4, scheduled_slot: 1,
    concern: '体力の衰えを感じるが、運動を始めるほどではないと思っている',
    reason_to_watch: '日常動作がそのままテストになる、今すぐ試せる参加型',
    core_message: '日常の何気ない動作こそ、バランスと連動性のテスト',
    takeaway: '片脚で靴下が履けない=バランスと股関節の連動に伸びしろがある',
    hook_visual: '立ったまま片脚を上げて靴下をスッと履く(ノーカット)',
    hook_line: '壁に触らずに、立ったまま靴下履けますか?',
    moves: ['片脚立ちでの靴下履き', '補助練習(片脚バランス→膝引き上げ)'],
    camera_angles: '全身が入る正面固定(ノーカットが信頼になる)',
    comparison_footage: 'ふらつく例と安定する例',
    structure: '0-3秒 実演フック → 3-15秒 視聴者に試させる → 15-35秒 できない理由(バランス+股関節連動) → 35-50秒 補助練習を1つ → 締めの問い',
    talking_points: ['毎朝の動作がテストになる', 'ふらつくのは老化ではなく使っていないだけ', '練習すれば戻る', '床の上での練習が近道'],
    avoid_misunderstanding: '年齢を煽らない(「何歳ならできるべき」と言わない)',
    safety_notes: 'ふらついたらすぐ足をつく。壁の近くで試す',
    closing_question: '今朝の靴下、どうやって履きましたか?',
    closing_style: '「明日の朝、思い出したら試してみてください」',
    comment_prompt: 'できた/ふらついた、正直にコメントどうぞ',
    keywords: ['片脚立ち', 'バランス テスト', '靴下 立って履く'],
    lesson_cta: false, duration_sec: 45, shoot_difficulty: 1, edit_difficulty: 1,
    values_used: ['practical', 'surprise', 'body_awareness', 'clarity'],
    scores: s({ target_clarity: 3, concern_specificity: 2, hook_strength: 3, visual_value: 2, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '再生数・新規視聴者',
    repurpose: 'WF-001と合わせて「日常テスト」シリーズの柱になる',
  },
  {
    code: 'WF-014', title: 'デスクワークの肩まわり、床で3つだけ', status: 'adopted',
    style: 'A', purpose_main: 'save', pillar_main: 'technique', audience: 'lifter',
    scheduled_week: 4, scheduled_slot: 2,
    concern: 'デスクワークで肩まわりが重い。ジムでは大きい筋肉ばかりで肩甲骨は放置',
    reason_to_watch: '仕事終わりに床で3つやるだけの保存版ルーティン',
    core_message: '肩まわりの重さは肩甲骨が「動いていない」サイン。床で動かし方を取り戻す',
    takeaway: '肩甲骨を寄せる・離す・回すの3方向を床で動かすと肩まわりが軽くなる',
    hook_visual: '四つ這いで肩甲骨だけがグッと盛り上がる背面アップ',
    hook_line: '一日デスクワークだった人、肩甲骨、今日一度も動かしていませんよ',
    moves: ['スキャプラプッシュ', '四つ這いでの肩甲骨の寄せ・離し', 'スレッドザニードル(胸椎回旋)'],
    camera_angles: '背面アップ+横からの全身',
    comparison_footage: 'なし',
    structure: '0-3秒 背面アップフック → 3-15秒 動いていない自覚を促す → 15-50秒 3ムーブを各10秒実演 → 50-60秒 寝る前でもできる → 保存訴求',
    talking_points: ['ベンチプレスでは肩甲骨は固定される', '固定と分離の両方できて自由になる', '3つで2分かからない', '仕事終わりの床時間のすすめ'],
    avoid_misunderstanding: '「肩こりが治る」という医学的断言をしない(軽くなる・動く感覚、で表現)',
    safety_notes: '首まで一緒に動かさない。痛みがあれば中止',
    closing_question: '今日、肩甲骨を何回動かしましたか?',
    closing_style: '「保存して、今夜の床で試してください」',
    comment_prompt: 'やってみた感想を「軽い/変わらない」で正直にコメントください',
    keywords: ['肩甲骨 はがし', 'デスクワーク 肩', '胸椎 回旋'],
    lesson_cta: false, duration_sec: 60, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['practical', 'expertise', 'info_density', 'body_awareness'],
    scores: s({ target_clarity: 3, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '保存数・再視聴',
    repurpose: '「デスクワークの床リセット」シリーズ(腰・股関節版)に展開',
  },
  {
    code: 'WF-015', title: '重い荷物、身体は持ち上げ方を知っている', status: 'adopted',
    style: 'C', purpose_main: 'persona', pillar_main: 'application', audience: 'beginner',
    scheduled_week: 4, scheduled_slot: 3,
    concern: '運動は生活と別物だと思っていて、優先順位が上がらない',
    reason_to_watch: '「運動=生活の動き」という視点の転換を、遊び心のある実演で見せる',
    core_message: 'トレーニングは生活から切り離されたものではなく、生活の動きの練習',
    takeaway: '床から物を拾う動作は毎日のスクワット。生活は練習場になる',
    hook_visual: '床の荷物を腰から曲げて持つ(NG)→しゃがんで持つ(OK)をテンポよく',
    hook_line: 'その持ち上げ方、腰が仕事しすぎです',
    moves: ['ヒップヒンジとスクワットの使い分け', '荷物を使った実演(買い物袋など生活小物)'],
    camera_angles: '横からの全身(腰の角度が見える位置)',
    comparison_footage: '腰から曲げる vs 股関節からしゃがむ',
    structure: '0-3秒 NG/OK比較フック → 3-20秒 なぜ腰にくるのか(股関節が休んでいる) → 20-40秒 生活の中の「実は練習になる動作」を2〜3個テンポよく → 40-55秒 生活を練習場にするという考え → 締め',
    talking_points: ['床の物を拾う=スクワット', '高い棚=カーフレイズとリーチ', '生活の動きを丁寧にやるだけで身体は変わり始める', '専用の時間が取れない人こそこの発想'],
    avoid_misunderstanding: '腰痛の治療・予防効果の断言をしない',
    safety_notes: '重い物の実演は無理のない重量で',
    closing_question: 'あなたの生活の中の「実は練習になっている動作」はどれですか?',
    closing_style: '「生活が練習場なら、今日からもう始まっています」',
    comment_prompt: '生活の中で身体を使う場面、コメントで教えてください',
    keywords: ['持ち上げ方', 'ヒップヒンジ', '日常 トレーニング'],
    lesson_cta: false, duration_sec: 55, shoot_difficulty: 1, edit_difficulty: 2,
    values_used: ['practical', 'relatability', 'rare_angle', 'calm_world'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 3, visual_value: 2, takeaway_value: 3, originality: 2, brand_fit: 3, filmability: 3 }),
    primary_metric: '平均視聴時間・共感コメント',
    repurpose: '「生活は練習場」シリーズ化。家事・通勤・階段など無限に展開可能',
  },
  {
    code: 'WF-016', title: '練習、失敗ばかりです', status: 'adopted',
    style: 'C', purpose_main: 'trust', pillar_main: 'backstage', audience: 'hesitant',
    scheduled_week: 4, scheduled_slot: 4,
    needs_material: true,
    production_status: 'awaiting_material',
    required_materials: '実際の練習の失敗映像: ①動きを間違えた ②左右が分からなくなった ③途中で止まった ④フォームを見返して修正した、の各カット/同じ動きの成功映像との比較/本人が実際に感じたことのメモ。【厳守】存在しない失敗を再現して実際の失敗として扱わない。演出で再現する場合は動画内に「再現」と明記',
    alternative_note: '素材が揃わない場合の代替: WF-023「Level 1で最初に習うこと」(保留中)の冒頭を設計し直して繰り上げ、またはWF-012型の方針語り企画を新規設計(いずれも信頼枠)',
    concern: '発信者は完璧に見えて、自分との距離を感じる',
    reason_to_watch: 'インストラクター側のNG集という珍しい裏側。親近感と信頼の両取り',
    core_message: '教える側も失敗しながら練習している。だから初心者の詰まりが分かる',
    takeaway: '失敗は上達の通過点。先生の失敗を見られる場所は安心できる',
    hook_visual: '転がる・崩れる・バランスを崩すNGカットを3連発',
    hook_line: '全部、今週の私です',
    moves: ['(NG集)練習中の失敗カット', '同じ動きの成功カット1つ'],
    camera_angles: '練習の定点記録から抜粋(日頃から回しておく)',
    comparison_footage: '同じ動きの失敗→成功',
    structure: '0-5秒 NG3連発 → 5-20秒 「教える側も失敗する」という話 → 20-40秒 失敗から何を調整したかを1つだけ具体的に → 40-55秒 だからレッスンでは詰まる場所が分かる → 締め',
    talking_points: ['失敗は隠すものではなく素材', 'どこで崩れたかが一番の情報', '自分が詰まった場所は教えるときの地図になる', '完璧な先生より、通ってきた先生'],
    avoid_misunderstanding: '「危ない失敗を真似していい」と思われないこと(安全な失敗だけ使う)',
    safety_notes: '危険な失敗カット(頭から落ちる等)は使わない',
    closing_question: 'あなたの最近の「いい失敗」はなんですか?',
    closing_style: '「来週も失敗します」と笑って締める',
    comment_prompt: '見たい「裏側」があればコメントでリクエストください',
    keywords: ['NG集', '練習 失敗', 'Animal Flow 練習風景'],
    lesson_cta: true,
    lesson_cta_phrase: 'こういう先生でよければ、レッスンの詳細はプロフィールのサイトからどうぞ',
    duration_sec: 55, shoot_difficulty: 2, edit_difficulty: 2,
    values_used: ['relatability', 'growth', 'calm_world', 'firsthand'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 3, visual_value: 2, takeaway_value: 2, originality: 3, brand_fit: 3, filmability: 2 }),
    primary_metric: 'プロフィール閲覧・サイト遷移',
    repurpose: '月1の定番企画にできる(NG素材は日々の練習を定点で回しておけば自動的に貯まる)',
    remake_note: '素材待ち: W1〜W3の練習・撮影を定点録画しておけば、W4までに実際の失敗素材が自然に揃う',
  },
];

// ═══ 保留14案(中核項目のみ) ═══════════════════════════

const HOLD: SeedEntry[] = [
  { code: 'WF-017', title: '呼吸が浅い日の、床での深呼吸', status: 'hold', style: 'B', purpose_main: 'persona', pillar_main: 'mind', audience: 'calm',
    concern: '呼吸が浅い気がする・落ち着く時間がない', values_used: ['calm_world', 'practical', 'body_awareness'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 1, visual_value: 1, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: 冒頭の絵が弱い。WF-007の反応を見てフックを設計し直してから' },
  { code: 'WF-018', title: 'チーターは90秒でバテる', status: 'hold', style: 'C', purpose_main: 'awareness', pillar_main: 'ability', audience: 'beginner',
    concern: '自分の身体の特性(強み弱み)を知らない', values_used: ['surprise', 'info_density', 'body_awareness'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 3, visual_value: 1, takeaway_value: 2, originality: 2, brand_fit: 2, filmability: 3 }),
    reject_reason: '保留: 雑学型は実演の画が弱い。動物映像素材の目処が立ってから。サイトの野生診断との導線設計もセットで' },
  { code: 'WF-019', title: 'ジムに行かない日の5分メニュー', status: 'hold', style: 'A', purpose_main: 'save', pillar_main: 'beginner', audience: 'lifter',
    concern: 'ジム休みの日に何もしない罪悪感', values_used: ['practical', 'info_density', 'expertise'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 1, brand_fit: 2, filmability: 3 }),
    reject_reason: '保留: 独自性が弱く既存の類似コンテンツ多数。wild-flowらしい切り口(動物・使い方)を足して再設計' },
  { code: 'WF-020', title: 'Crabで足首がつかめない理由', status: 'hold', style: 'A', purpose_main: 'save', pillar_main: 'technique', audience: 'hesitant',
    concern: 'Crab系の動きで手が届かない・窮屈', values_used: ['expertise', 'clarity', 'body_awareness'],
    scores: s({ target_clarity: 2, concern_specificity: 3, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: 良企画だがWF-002(Beast基礎)の後に出す方が文脈が通る。第2バッチ候補' },
  { code: 'WF-021', title: 'バドミントン選手の股関節はなぜ大事か', status: 'hold', style: 'C', purpose_main: 'trust', pillar_main: 'application', audience: 'athlete',
    concern: '股関節の硬さがプレーの幅を狭めている', values_used: ['firsthand', 'expertise', 'practical'],
    scores: s({ target_clarity: 3, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 2, filmability: 2 }),
    materialTitles: ['バドミントン競技の本人経験(左右差・切り返し・体重移動・連動)'],
    reject_reason: '保留: 本人の競技経験としての使用は承認済み(2026-07-27再審査)。撮影設計図が未作成のため保留継続。WF-008の反応を見て競技シリーズ2作目として設計図を作ってから候補化' },
  { code: 'WF-022', title: '腰が重い日の床リセット', status: 'hold', style: 'A', purpose_main: 'save', pillar_main: 'technique', audience: 'beginner',
    concern: '夕方になると腰まわりが固まる', values_used: ['practical', 'clarity', 'body_awareness'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 1, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: WF-014(肩)の反応が良ければ「床リセット」シリーズ2作目として。医学的表現の設計に注意' },
  // 【監査による変更】Level 1認定インストラクターであることは本人明示で確定(素材DB登録済み)。
  // 資格保有の事実には触れてよい。ただし取得日・場所・講師名・講習の具体的内容・試験内容は
  // 未提供のため語れない。保留理由は「冒頭が弱い(1点)」の設計課題のみに変更。
  { code: 'WF-023', title: 'Level 1で最初に習うこと', status: 'hold', style: 'B', purpose_main: 'trust', pillar_main: 'backstage', audience: 'hesitant',
    concern: '資格や体系がある運動なのか分からず信頼しきれない', values_used: ['expertise', 'firsthand', 'clarity'],
    materialTitles: ['Animal Flow Level 1 認定インストラクター(資格保有の事実)'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 1, visual_value: 1, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: 資格保有は本人確認済み。冒頭の強さ(1点)と視覚価値(1点)の設計を改善してから候補化。講習中の具体的なエピソードを話す場合は「Level 1認定取得時の経験」素材の本人登録が別途必要' },
  { code: 'WF-024', title: '子どもと床で遊ぶ動物の動き', status: 'hold', style: 'A', purpose_main: 'awareness', pillar_main: 'application', audience: 'beginner',
    concern: '子どもと遊ぶ体力がない・遊び方が分からない', values_used: ['relatability', 'rare_angle', 'practical'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 3, brand_fit: 3, filmability: 1 }),
    reject_reason: '保留: 差別化は強いが子役の撮影協力が必要で一人撮影不可。体制が整ったら' },
  { code: 'WF-025', title: '夜、電気を落として動く10分', status: 'hold', style: 'B', purpose_main: 'save', pillar_main: 'mind', audience: 'calm',
    concern: '寝る前スマホがやめられず入眠が悪い', values_used: ['calm_world', 'practical', 'visual_pleasure'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 3, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 2 }),
    reject_reason: '保留: 暗所撮影の照明設計が必要。画作りをテストしてから' },
  { code: 'WF-026', title: '逆立ちできなくていい、という話', status: 'hold', style: 'B', purpose_main: 'persona', pillar_main: 'mind', audience: 'hesitant',
    concern: '派手な技ができないと発信も上達も意味がない気がする', values_used: ['calm_world', 'relatability', 'body_awareness'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 1, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: WF-007と主張が近く、同月に出すと重複感。翌月以降に間隔を空けて' },
  { code: 'WF-027', title: '筋トレ前の2分アクティベーション', status: 'hold', style: 'A', purpose_main: 'save', pillar_main: 'application', audience: 'lifter',
    concern: 'ウォームアップを何となくで済ませている', values_used: ['practical', 'expertise', 'info_density'],
    scores: s({ target_clarity: 3, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 2, filmability: 3 }),
    reject_reason: '保留: WF-005(筋トレ勢向け)の反応を見てからシリーズ化判断' },
  { code: 'WF-028', title: '寝る前90秒で、翌朝が少し変わる', status: 'hold', style: 'A', purpose_main: 'save', pillar_main: 'beginner', audience: 'calm',
    concern: '朝起きた時の身体の重さ', values_used: ['practical', 'calm_world', 'clarity'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 1, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: WF-006(朝1分)と生活隙間シリーズとして統合設計してから出す' },
  { code: 'WF-029', title: '四足歩行だけで体幹は鍛えられるのか', status: 'hold', style: 'C', purpose_main: 'awareness', pillar_main: 'ability', audience: 'lifter',
    concern: '自重・床トレの負荷への疑い', values_used: ['surprise', 'expertise', 'challenge'],
    scores: s({ target_clarity: 2, concern_specificity: 2, hook_strength: 2, visual_value: 2, takeaway_value: 2, originality: 2, brand_fit: 2, filmability: 3 }),
    reject_reason: '保留: 「鍛えられる/られない」の二項対立は煽りに寄りやすい。問いの立て方を再設計' },
  { code: 'WF-030', title: '身体が硬い人ほど、伸びしろが見える', status: 'hold', style: 'B', purpose_main: 'persona', pillar_main: 'mind', audience: 'hesitant',
    concern: '身体が硬いことがコンプレックスで始められない', values_used: ['relatability', 'calm_world', 'body_awareness'],
    scores: s({ target_clarity: 2, concern_specificity: 3, hook_strength: 2, visual_value: 1, takeaway_value: 2, originality: 2, brand_fit: 3, filmability: 3 }),
    reject_reason: '保留: メッセージは強いが具体的な動作が薄く精神論に寄っている。実演パートを設計してから' },
];

// ═══ 却下10案(理由の記録) ═══════════════════════════════

const REJECTED: SeedEntry[] = [
  { code: 'WF-031', title: '毎日やれば1ヶ月で誰でもマスター', status: 'rejected', purpose_main: 'awareness', pillar_main: 'growth', audience: 'hesitant',
    values_used: ['challenge', 'growth'],
    reject_reason: '却下: 品質ルール違反(誰でも同じ期間で習得できると断言している)' },
  { code: 'WF-032', title: '腰痛が治る魔法の動き', status: 'rejected', purpose_main: 'save', pillar_main: 'technique', audience: 'beginner',
    values_used: ['practical'],
    reject_reason: '却下: 品質ルール違反(医学的効果・治療効果の断言)。「腰が軽くなる床の動き」として再設計するならリメイク可' },
  { code: 'WF-033', title: 'ジムより効率的なAnimal Flow', status: 'rejected', purpose_main: 'awareness', pillar_main: 'ability', audience: 'lifter',
    values_used: ['surprise', 'expertise'],
    reject_reason: '却下: 品質ルール違反(他の運動方法の否定)。ブランド方針は筋トレとの掛け算' },
  { code: 'WF-034', title: 'かっこいいフロー10連発', status: 'rejected', purpose_main: 'awareness', pillar_main: 'growth', audience: 'hesitant',
    values_used: ['visual_pleasure', 'production'],
    reject_reason: '却下: 価値2つ(3つ未満)・持ち帰りなし。見栄えだけの企画は作らない方針にも抵触' },
  { code: 'WF-035', title: 'しゃがめるかテスト・第2弾', status: 'rejected', purpose_main: 'awareness', pillar_main: 'beginner', audience: 'beginner',
    concern: '運動不足の自覚はあるが衰えの程度が分からない', values_used: ['practical', 'clarity', 'body_awareness'],
    reject_reason: '却下: WF-001と重複(視聴者・悩み・メッセージ・目的が一致)。WF-001の結果が出てからリメイク判断' },
  { code: 'WF-036', title: '上海ストーリー完全版(10分)', status: 'rejected', purpose_main: 'persona', pillar_main: 'mind', audience: 'calm',
    values_used: ['experience', 'relatability', 'firsthand'],
    reject_reason: '却下: ショート動画の尺・PF特性に不適合。ブログ/note長文向き。WF-003で反応を見てから長尺化を検討' },
  { code: 'WF-037', title: 'フォロワー参加型30日企画', status: 'rejected', purpose_main: 'awareness', pillar_main: 'growth', audience: 'beginner',
    values_used: ['challenge', 'growth', 'relatability'],
    reject_reason: '却下: フォロワー基盤がまだなく参加が成立しない。撮影・運営コストも高い。半年後に再検討' },
  { code: 'WF-038', title: 'FSS理論から学ぶ動きの科学', status: 'rejected', purpose_main: 'save', pillar_main: 'technique', audience: 'lifter',
    values_used: ['expertise', 'info_density'],
    reject_reason: '却下: 対象が曖昧で初心者に難しすぎる。専門用語の正式な定義確認(事実確認)も必要' },
  { code: 'WF-039', title: 'レッスン申込み受付中のお知らせ', status: 'rejected', purpose_main: 'trust', pillar_main: 'backstage', audience: 'hesitant',
    values_used: [],
    reject_reason: '却下: 視聴者価値ゼロの告知のみ・導線が強すぎる。信頼構築はWF-004/012/016型で行う' },
  // 【監査による変更】却下→リメイク候補。Level 1認定保有は確定したため「資格がない前提の却下」は誤り。
  // ただし指導人数・実績数値・取得エピソードは未提供のため、それらを語る形ではまだ作れない。
  { code: 'WF-040', title: '私がAnimal Flowを教えられる理由(実績紹介)', status: 'remake', purpose_main: 'trust', pillar_main: 'backstage', audience: 'hesitant',
    values_used: ['expertise', 'firsthand'], needs_material: true,
    materialTitles: ['Animal Flow Level 1 認定インストラクター(資格保有の事実)'],
    reject_reason: 'リメイク候補: Level 1認定保有は確定(語ってよい)。ただし指導実績の数値・取得時のエピソードは未提供のため創作不可。実績を語らない「資格の事実+教え方の考え」構成に再設計するか、本人が実績素材を登録してから',
    remake_note: '一次情報の追加が必要: 指導人数・取得時の経験談(本人提供待ち)' },
];

/** 素材タイトル→id を解決して IdeaDraft 40件を作る */
const MATERIAL_TITLE_ALIASES: Record<string, string> = {
  // 20260727b 適用前のDBでは旧タイトルのままの可能性があるため両対応
  'バドミントン競技の本人経験(左右差・切り返し・体重移動・連動)': 'バドミントンコミュニティの主宰経験',
};

export function buildSeedDrafts(materials: Material[]): IdeaDraft[] {
  const byTitle = new Map(materials.map(m => [m.title, m.id]));
  const resolve = (t: string) => byTitle.get(t) ?? byTitle.get(MATERIAL_TITLE_ALIASES[t] ?? '');
  const all = [...ADOPTED, ...HOLD, ...REJECTED];
  return all.map(entry => {
    const { materialTitles, ...rest } = entry;
    const material_ids = (materialTitles ?? [])
      .map(resolve)
      .filter((x): x is string => !!x);
    const draft: IdeaDraft = { ...BASE, ...rest, material_ids };
    // score_total はコード側で再計算(seed値も信用しない)
    draft.score_total = Object.values(draft.scores).reduce(
      (sum, v) => sum + (typeof v === 'number' ? Math.max(0, Math.min(3, v)) : 0), 0);
    return draft;
  });
}

/** 実ステータスベースの内訳(監査でADOPTED配列内にも保留が混在するため配列長ではなく状態で数える) */
export function seedCounts(): Record<string, number> {
  const all = [...ADOPTED, ...HOLD, ...REJECTED];
  const counts: Record<string, number> = {};
  for (const e of all) {
    const st = e.status ?? 'candidate';
    counts[st] = (counts[st] ?? 0) + 1;
  }
  counts.total = all.length;
  return counts;
}
